### ISSUE TITLE
Does it consume account bandwith?

### ISSUE THREAD

**Issue by askfriends** [marcussacana/DriveMirror#2]
Hi..
it seems to be very useful script. thanks for making it.

I want to know does it consume account bandwidth? as you might know that google drive allows 750gb per account copy limit. So this script also consume that limit or it doesnt consume that??

Also add "How to use it" in readme file, it will help newbies like me.
thanks again

**Comment by marcussacana** [comment]
Yeah, you can't copy more than 750gb per day.

**Comment by marcussacana** [comment]
That said, if you use a shared drive and maybe changing the api key you can bypass this limit.

**Comment by askfriends** [comment]
owh..thanks anyway
